//
//  ClipboardService.swift
//  boringNotch — adapted from Maccy Clipboard.swift
//

import AppKit
import Defaults
import Sauce

@MainActor
final class ClipboardService {
    static let shared = ClipboardService()

    typealias OnNewCopyHook = (HistoryItem) -> Void

    private var onNewCopyHooks: [OnNewCopyHook] = []
    var changeCount: Int

    private let pasteboard = NSPasteboard.general
    private var timer: Timer?

    private let dynamicTypePrefix = "dyn."
    private let microsoftSourcePrefix = "com.microsoft.ole.source."
    private let supportedTypes: Set<NSPasteboard.PasteboardType> = [
        .fileURL, .html, .heic, .image, .jpeg, .png, .rtf, .string, .tiff
    ]
    private let ignoredTypes: Set<NSPasteboard.PasteboardType> = [
        .autoGenerated, .concealed, .transient
    ]

    private var enabledTypes: Set<NSPasteboard.PasteboardType> {
        // Keep image capture enabled for preferences written before jpeg/heic/public.image
        // were supported. The app has no per-format clipboard toggle, so this is a safe migration.
        Defaults[.clipboardEnabledPasteboardTypes]
            .union(ClipboardStorageType.images.types)
    }
    private var disabledTypes: Set<NSPasteboard.PasteboardType> {
        supportedTypes.subtracting(enabledTypes)
    }

    private var sourceApp: NSRunningApplication? { NSWorkspace.shared.frontmostApplication }

    private init() {
        changeCount = pasteboard.changeCount
    }

    func onNewCopy(_ hook: @escaping OnNewCopyHook) {
        onNewCopyHooks.append(hook)
    }

    func clearHooks() {
        onNewCopyHooks = []
    }

    func start() {
        guard Defaults[.clipboardEnabled] else { return }
        timer?.invalidate()
        timer = Timer.scheduledTimer(
            timeInterval: Defaults[.clipboardCheckInterval],
            target: self,
            selector: #selector(checkForChangesInPasteboard),
            userInfo: nil,
            repeats: true
        )
        RunLoop.main.add(timer!, forMode: .common)
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    func restart() {
        stop()
        start()
    }

    func copy(_ item: HistoryItem?, removeFormatting: Bool = false) {
        guard let item else { return }

        pasteboard.clearContents()
        var contents = item.contents

        if removeFormatting {
            contents = clearFormatting(contents)
        }

        for content in contents {
            guard content.type != NSPasteboard.PasteboardType.fileURL.rawValue else { continue }
            pasteboard.setData(content.value, forType: NSPasteboard.PasteboardType(content.type))
        }

        let fileURLItems: [NSPasteboardItem] = contents.compactMap { content in
            guard content.type == NSPasteboard.PasteboardType.fileURL.rawValue else { return nil }
            guard let value = content.value else { return nil }
            let pasteItem = NSPasteboardItem()
            pasteItem.setData(value, forType: NSPasteboard.PasteboardType(content.type))
            return pasteItem
        }
        pasteboard.writeObjects(fileURLItems)

        pasteboard.setString("", forType: .fromMaccy)
        pasteboard.setString(item.application ?? "", forType: .source)
        sync()
        changeCount = pasteboard.changeCount
    }

    /// Synthesize Cmd+V into the previously frontmost application.
    func paste() {
        // On first paste without AX trust, prompt the user (Maccy-style Accessibility).
        if !ClipboardAccessibility.isTrusted {
            ClipboardAccessibility.requestIfNeeded()
        }
        ClipboardAccessibility.check()

        let cmdFlag = CGEventFlags(rawValue: UInt64(NSEvent.ModifierFlags.command.rawValue) | 0x000008)
        var vCode = Sauce.shared.keyCode(for: .v)

        if KeyboardLayout.current.commandSwitchesToQWERTY && cmdFlag.contains(.maskCommand) {
            vCode = Key.v.QWERTYKeyCode
        }

        let source = CGEventSource(stateID: .combinedSessionState)
        source?.setLocalEventsFilterDuringSuppressionState(
            [.permitLocalMouseEvents, .permitSystemDefinedEvents],
            state: .eventSuppressionStateSuppressionInterval
        )

        let keyVDown = CGEvent(keyboardEventSource: source, virtualKey: vCode, keyDown: true)
        let keyVUp = CGEvent(keyboardEventSource: source, virtualKey: vCode, keyDown: false)
        keyVDown?.flags = cmdFlag
        keyVUp?.flags = cmdFlag
        keyVDown?.post(tap: .cgSessionEventTap)
        keyVUp?.post(tap: .cgSessionEventTap)
    }

    func clearSystemClipboardIfNeeded() {
        guard Defaults[.clipboardClearSystemClipboard] else { return }
        pasteboard.clearContents()
    }

    @objc
    func checkForChangesInPasteboard() {
        guard Defaults[.clipboardEnabled] else { return }
        guard pasteboard.changeCount != changeCount else { return }

        changeCount = pasteboard.changeCount

        if pasteboard.pasteboardItems?.contains(where: { $0.types.contains(.fromMaccy) }) == true {
            // Our own write — skip re-recording as a new external copy
            return
        }

        // Pause capture while ignoreEvents is on; optionally consume only the next event.
        if Defaults[.clipboardIgnoreEvents] {
            if Defaults[.clipboardIgnoreOnlyNextEvent] {
                Defaults[.clipboardIgnoreEvents] = false
                Defaults[.clipboardIgnoreOnlyNextEvent] = false
            }
            return
        }

        if shouldIgnore(Set(pasteboard.types ?? [])) {
            return
        }

        if let sourceAppBundle = sourceApp?.bundleIdentifier, shouldIgnore(sourceAppBundle) {
            return
        }

        var contents = [HistoryItemContent]()
        pasteboard.pasteboardItems?.forEach { item in
            var types = Set(item.types)
            if types.contains(.string) && isEmptyString(item) && !richText(item) {
                return
            }

            if shouldIgnore(item) {
                return
            }

            types = types
                .subtracting(disabledTypes)
                .filter { !$0.rawValue.starts(with: dynamicTypePrefix) }
                .filter { !$0.rawValue.starts(with: microsoftSourcePrefix) }

            if types.isSuperset(of: [.microsoftLinkSource, .microsoftObjectLink]) {
                types = types.subtracting([.microsoftLinkSource, .microsoftObjectLink])
            }

            types.forEach { type in
                contents.append(HistoryItemContent(type: type.rawValue, value: item.data(forType: type)))
            }
        }

        guard !contents.isEmpty else { return }

        let historyItem = HistoryItem(contents: contents)
        historyItem.application = sourceApp?.bundleIdentifier
        historyItem.title = historyItem.generateTitle()

        onNewCopyHooks.forEach { $0(historyItem) }
    }

    private func shouldIgnore(_ types: Set<NSPasteboard.PasteboardType>) -> Bool {
        let ignoredTypes = self.ignoredTypes
            .union(Defaults[.clipboardIgnoredPasteboardTypes].map { NSPasteboard.PasteboardType($0) })

        return types.isDisjoint(with: enabledTypes) ||
            !types.isDisjoint(with: ignoredTypes)
    }

    private func shouldIgnore(_ sourceAppBundle: String) -> Bool {
        if Defaults[.clipboardIgnoreAllAppsExceptListed] {
            // Whitelist mode: ignore everything except listed apps
            return !Defaults[.clipboardIgnoredApps].contains(sourceAppBundle)
        } else {
            // Blacklist mode: ignore only listed apps
            return Defaults[.clipboardIgnoredApps].contains(sourceAppBundle)
        }
    }

    private func shouldIgnore(_ item: NSPasteboardItem) -> Bool {
        for regexp in Defaults[.clipboardIgnoreRegexp] {
            if let string = item.string(forType: .string) {
                do {
                    let regex = try NSRegularExpression(pattern: regexp)
                    if regex.numberOfMatches(in: string, range: NSRange(string.startIndex..., in: string)) > 0 {
                        return true
                    }
                } catch {
                    return false
                }
            }
        }
        return false
    }

    private func isEmptyString(_ item: NSPasteboardItem) -> Bool {
        guard let string = item.string(forType: .string) else { return true }
        return string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
    }

    private func richText(_ item: NSPasteboardItem) -> Bool {
        if let rtf = item.data(forType: .rtf),
           let attributedString = NSAttributedString(rtf: rtf, documentAttributes: nil) {
            return !attributedString.string.isEmpty
        }
        if let html = item.data(forType: .html),
           let attributedString = NSAttributedString(html: html, documentAttributes: nil) {
            return !attributedString.string.isEmpty
        }
        return false
    }

    private func sync() {
        guard let app = sourceApp,
              app.bundleURL?.lastPathComponent == "Chrome Remote Desktop.app" ||
                app.localizedName?.contains("NetBeans") == true else {
            return
        }
        NSApp.activate(ignoringOtherApps: true)
        NSApp.hide(nil)
    }

    private func clearFormatting(_ contents: [HistoryItemContent]) -> [HistoryItemContent] {
        var newContents: [HistoryItemContent] = contents
        let stringContents = contents.filter { NSPasteboard.PasteboardType($0.type) == .string }
        if !stringContents.isEmpty {
            newContents = stringContents
            let fileURLContents = contents.filter { NSPasteboard.PasteboardType($0.type) == .fileURL }
            if !fileURLContents.isEmpty {
                newContents += fileURLContents
            }
        }
        return newContents
    }
}
