//
//  PasteboardTypes.swift
//  boringNotch — ported from Maccy
//

import AppKit.NSPasteboard
import Defaults
import UniformTypeIdentifiers

extension NSPasteboard.PasteboardType: Defaults.Serializable {
    static let heic = NSPasteboard.PasteboardType(rawValue: "public.heic")
    static let jpeg = NSPasteboard.PasteboardType(rawValue: "public.jpeg")
    static let image = NSPasteboard.PasteboardType(rawValue: UTType.image.identifier)
    static let universalClipboard = NSPasteboard.PasteboardType(rawValue: "com.apple.is-remote-clipboard")

    static let autoGenerated = NSPasteboard.PasteboardType(rawValue: "org.nspasteboard.AutoGeneratedType")
    static let concealed = NSPasteboard.PasteboardType(rawValue: "org.nspasteboard.ConcealedType")
    static let source = NSPasteboard.PasteboardType(rawValue: "org.nspasteboard.source")
    static let transient = NSPasteboard.PasteboardType(rawValue: "org.nspasteboard.TransientType")

    static let modified = NSPasteboard.PasteboardType(rawValue: "x.nspasteboard.ModifiedType")
    static let fromMaccy = NSPasteboard.PasteboardType(rawValue: "org.p0deje.Maccy")

    static let microsoftObjectLink = NSPasteboard.PasteboardType(rawValue: "com.microsoft.ObjectLink")
    static let microsoftLinkSource = NSPasteboard.PasteboardType(rawValue: "com.microsoft.Link-Source")

    static let linkPresentationMetadata = NSPasteboard.PasteboardType(rawValue: "com.apple.linkpresentation.metadata")
    static let customWebKitPasteboardData = NSPasteboard.PasteboardType(rawValue: "com.apple.WebKit.custom-pasteboard-data")

    static let customChromiumWebData = NSPasteboard.PasteboardType(rawValue: "org.chromium.web-custom-data")
    static let chromiumSourceUrl = NSPasteboard.PasteboardType(rawValue: "org.chromium.source-url")
    static let chromiumSourceToken = NSPasteboard.PasteboardType(rawValue: "org.chromium.internal.source-rfh-token")

    static let notesRichText = NSPasteboard.PasteboardType(rawValue: "com.apple.notes.richtext")
}

struct ClipboardStorageType {
    static let files = ClipboardStorageType(types: [.fileURL])
    static let images = ClipboardStorageType(types: [.png, .tiff, .jpeg, .heic, .image])
    static let text = ClipboardStorageType(types: [.html, .rtf, .string])
    static let all = ClipboardStorageType(types: files.types + images.types + text.types)

    var types: [NSPasteboard.PasteboardType]
}
